### ISSUE TITLE
create homebrew installers

### ISSUE THREAD

**Issue by maximilien** [maximilien/i18n4go#29]
1. Add scripts:

```
installers/homebrew/i18n4go-bin.rb
installers/homebrew/i18n4go-src.rb
```

2. submit to the Homebrew project
3. update README.md with new Homebrew

**Comment by maximilien** [comment]
@XenoPhex,

I recalled you had created or planned to create homebrew installers for `i18n4go`. Correct?

Did you ever get a chance to create these? Either case, let me know. I plan to create some following the CF CLI.

Thanks for any replies. Best,

@maximilien

**Comment by XenoPhex** [comment]
@maximilien I only made a formula for the CLI, but it was rejected a few times due to the dependency on godeps and something else. But you can get around that now as the go community now recommends just vendering your deps and compiling things straight.

A lot of the problems I had submitting my formula for the CLI had to do with the 'requirements' they had for formulas on the main channel.

**Comment by maximilien** [comment]
Thanks for response @XenoPhex.

I created initial ones on this branch. Want to try it and let me know if that makes sense to submit.

Best,

@maximilien

**Comment by XenoPhex** [comment]
Looks like there's a few issues with the installer script:

- Looks like you're downloading version [0.2.0](https://github.com/maximilien/i18n4go/blob/issue29/installers/homebrew/i18n4go-bin.rb#L5), but the formula says you're installing [0.1.1](https://github.com/maximilien/i18n4go/blob/issue29/installers/homebrew/i18n4go-bin.rb#L7)
- The [SHA1](https://github.com/maximilien/i18n4go/blob/issue29/installers/homebrew/i18n4go-bin.rb#L6) seems to be off. This may be related to the previous poit, but I had to modify this line by hand in order to continue:
```
brew install ./installers/homebrew/i18n4go-bin.rb
==> Downloading https://github.com/maximilien/i18n4go/archive/v0.2.0.tar.gz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: f2c0073672be91c185f81d5c5bd747aa1763c393
Actual: f0e9af7879a85d7f7f180ff95bf4ae9928b4d59d
Archive: /Library/Caches/Homebrew/i18n4go-bin-0.1.1.tar.gz
To retry an incomplete download, remove the file above.
```
- The script itself doesn't seem to install properly, even after this change:
```
brew install ./installers/homebrew/i18n4go-bin.rbz
==> Downloading https://github.com/maximilien/i18n4go/archive/v0.2.0.tar.gz
######################################################################## 100.0%
==> curl -O https://raw.github.com/maximilien/i18n4go/v0.2.0/LICENSE
==> /usr/local/Cellar/i18n4go-bin/0.1.1/bin/build
2015-04-12 17:25:20 -0400

/usr/local/Cellar/i18n4go-bin/0.1.1/bin/build


READ THIS: https://git.io/brew-troubleshooting
```
Taking a look at the bin/build script, it looks like you have [an additional dependency on `godeps`](https://github.com/maximilien/i18n4go/blob/issue29/bin/build#L4). This dependency was an absolute blocker for us on the CLI and we ended up just releasing a formula that downloaded the binary as opposed to building it from source. I would say either remove this dependency from the script or use a different mechanism to set the `$GOPATH` when you don't have `godeps`.

- On an additional note, it may be worth adding a `head` parameter to your formula to point to the latest edge build (look at the [VIM](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/vim.rb#L3) formula for an example). This way if people want to get the latest version they can.

**Comment by maximilien** [comment]
@XenoPhex, thanks for detail response. Will try to update. Best.

**Comment by maximilien** [comment]
I am closing this issue because I added simple support for building/getting the `i18n4go` binary quickly via Go's `get` command. Just do:

```
$ go get github.com/maximilien/i18n4go/i18n4go
```

Also, I added a section in the [README](README.md) to explain how to do this.
